name: Release nuget
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
jobs:
  deployment:
    runs-on: windows-latest
    environment: nuget.org
    steps:      
      - uses: actions/checkout@v3

      - name: Creating packages and uploading them to nuget.org
        run: |
          dotnet pack .\src\LTest\LTest.csproj -c Release -o nupkgs -p:Version=${{ github.event.inputs.version }}
          dotnet pack .\src\LTest.Http\LTest.Http.csproj -c Release -o nupkgs -p:Version=${{ github.event.inputs.version }}
          dotnet pack .\src\LTest.EfCore\LTest.EfCore.csproj -c Release -o nupkgs -p:Version=${{ github.event.inputs.version }}
          cd nupkgs
          nuget push *.nupkg ${{ secrets.NUGET_KEY }} -Source https://api.nuget.org/v3/index.json
