name: Release NuGet
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: nuget.org
    permissions: write-all
    steps:      
      - uses: actions/checkout@v3

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.inputs.version }}',
              sha: context.sha
            })

      - name: Creating packages and uploading them to nuget.org
        run: |
          dotnet pack .\src\BulletProve.Base\BulletProve.Base.csproj -c Release -o nupkgs -p:Version=${{ github.event.inputs.version }}
          dotnet pack .\src\BulletProve.EfCore\BulletProve.EfCore.csproj -c Release -o nupkgs -p:Version=${{ github.event.inputs.version }}
          dotnet pack .\src\BulletProve.Http\BulletProve.Http.csproj -c Release -o nupkgs -p:Version=${{ github.event.inputs.version }}
          dotnet pack .\src\BulletProve.XUnit\BulletProve.XUnit.csproj -c Release -o nupkgs -p:Version=${{ github.event.inputs.version }}
          cd nupkgs
          nuget push *.nupkg ${{ secrets.NUGET_KEY }} -Source https://api.nuget.org/v3/index.json
